import * as fs from 'fs';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '../../..');
const PACKAGES_DIR = path.join(REPO_ROOT, 'packages');

/**
 * Self-contained tsconfig consumed by ArchUnitTS. Generated by
 * `scripts/build-arch-tsconfig.mjs` (run by the `arch` Nx target) from the
 * edition-aware effective config, so `@packmind/*` aliases resolve and the
 * monorepo sources are discovered. Paths in violations are relative to repo root
 * (e.g. `packages/recipes/src/...`), which is what the rule globs below match.
 */
export const ARCH_TSCONFIG = path.join(REPO_ROOT, 'tsconfig.arch.json');

/**
 * The ONLY hardcoded package list: packages excluded from architecture analysis
 * entirely. `ui` is the Chakra-based frontend component library — not a backend
 * hexagon, so the ports & adapters rules do not apply to it. Add a package here
 * only to opt it out completely.
 */
export const EXCLUDED_PACKAGES = new Set<string>(['ui']);

/**
 * Every package under `packages/` except the excluded ones, discovered from the
 * filesystem so new packages are covered automatically (no list to maintain).
 */
const ALL_PACKAGES: readonly string[] = fs
  .readdirSync(PACKAGES_DIR, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .filter((name) => !EXCLUDED_PACKAGES.has(name))
  .sort();

/**
 * Domain (hexagon) packages — the cross-domain isolation subjects. A package is
 * a domain when it owns a `src/domain/` layer (the ports & adapters marker).
 * They may only talk to each other through `@packmind/types` ports, never by
 * importing each other's source directly.
 *
 * Derived from structure on purpose so the only maintained list is
 * EXCLUDED_PACKAGES: a new domain package is picked up automatically, and
 * shared/leaf packages (types, logger, node-utils, test-utils, migrations,
 * editions, frontend, assets, linter-*) are recognised as non-domains because
 * they have no `domain/` layer — so importing them stays legal for everyone.
 *
 * A package that is *missing* its `domain/` layer is not fully invisible: the
 * layering and domain-purity rules still scan ALL packages via `packages/*`
 * globs.
 */
export const DOMAIN_PACKAGES: readonly string[] = ALL_PACKAGES.filter((name) =>
  fs.existsSync(path.join(PACKAGES_DIR, name, 'src', 'domain')),
);

/**
 * Glob fragments tolerant of the small folder-naming inconsistencies across
 * packages (e.g. `useCases` vs `usecases`, `adapter` vs `adapters`). Matched as
 * full repo-relative paths via `inPath`.
 */
export const LAYER_GLOBS = {
  // Use case classes — `useCases` (most) and `usecases` (spaces).
  useCases: 'packages/*/src/application/use[cC]ases/**',
  // Domain adapters — `adapter` (most) and `adapters` (spaces).
  adapters: 'packages/*/src/application/adapter*/**',
  // Application services.
  services: 'packages/*/src/application/services/**',
  // The whole application layer (use cases + adapters + services + jobs).
  application: 'packages/*/src/application/**',
  // Domain layer: entities, repository interfaces (ports), domain services.
  domain: 'packages/*/src/domain/**',
  // Infrastructure layer (repository implementations, TypeORM schemas, jobs).
  infra: 'packages/*/src/infra/**',
  // Concrete repository implementations only (NOT schemas/entities).
  repositories: 'packages/*/src/infra/repositories/**',
  // TypeORM EntitySchema definitions (pure ORM mapping).
  schemas: 'packages/*/src/infra/schemas/**',
  // The shared contract package (ports, contracts, events, entity types).
  types: 'packages/types/src/**',
  // The whole NestJS API app (controllers, modules, providers).
  apiAll: 'apps/api/src/**/*.ts',
} as const;

/**
 * Matches the source of ANY domain package. Used by reverse-dependency rules
 * (shared/base packages and the contract package must not depend on domains).
 * Built the same way as the per-domain target in `cross-domain.arch.spec.ts`.
 */
export const DOMAIN_SRC_REGEX = new RegExp(
  `packages/(${DOMAIN_PACKAGES.join('|')})/src/`,
);

/**
 * Matches the source of the shared/base packages that domains build on top of.
 * These must never depend back on a domain (would create a cycle / inversion).
 */
export const SHARED_BASE_REGEX = /packages\/(node-utils|logger)\/src\//;
